//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace galetova_22106_prilojenie.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhotocenterEntities : DbContext
    {
        public PhotocenterEntities()
            : base("name=PhotocenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Clienty> Clienty { get; set; }
        public virtual DbSet<Dolgnosti> Dolgnosti { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<Status_zakaza> Status_zakaza { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
        public virtual DbSet<Uslugi> Uslugi { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
        public virtual DbSet<Kolichestvo_tovara> Kolichestvo_tovara { get; set; }
        public virtual DbSet<Kolichestvo_uslug> Kolichestvo_uslug { get; set; }
    }
}
