//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace galetova_22106_prilojenie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uslugi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uslugi()
        {
            this.Kolichestvo_uslug = new HashSet<Kolichestvo_uslug>();
        }
    
        public int ID_uslugi { get; set; }
        public string Nazvanie_uslugi { get; set; }
        public decimal Cena_uslugi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kolichestvo_uslug> Kolichestvo_uslug { get; set; }
    }
}
