//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace galetova_22106_prilojenie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.Kolichestvo_tovara = new HashSet<Kolichestvo_tovara>();
            this.Kolichestvo_uslug = new HashSet<Kolichestvo_uslug>();
        }
    
        public int ID_zakaza { get; set; }
        public int ID_statusa_zakaza { get; set; }
        public int ID_clienta { get; set; }
        public int ID_sotrudnika { get; set; }
        public Nullable<decimal> Obshaya_cena { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Clienty Clienty { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Status_zakaza Status_zakaza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kolichestvo_tovara> Kolichestvo_tovara { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kolichestvo_uslug> Kolichestvo_uslug { get; set; }
    }
}
